"""
Quantum circuit representation and visualization for qubit-encoded quantum dynamics.

This module provides functionality to represent and visualize the quantum circuits
generated by the Suzuki-Trotter decomposition in the qubit simulator.
"""

import numpy as np
from typing import List, Tuple, Optional, Dict
import qutip as qt

# Import qiskit if available
try:
    from qiskit import QuantumCircuit as QiskitQuantumCircuit
    from qiskit.quantum_info import Operator
    QISKIT_AVAILABLE = True
except ImportError:
    QISKIT_AVAILABLE = False


class CircuitGate:
    """
    Represents a single quantum gate in a circuit.
    
    Attributes
    ----------
    name : str
        Name of the gate (e.g., 'RX', 'RY', 'RZ', 'CNOT')
    qubits : list of int
        List of qubit indices this gate acts on
    params : dict
        Parameters for the gate (e.g., rotation angles)
    matrix : Qobj, optional
        The unitary matrix representation of the gate
    """
    
    def __init__(self, name: str, qubits: List[int], params: Optional[Dict] = None, 
                 matrix: Optional[qt.Qobj] = None):
        """
        Initialize a circuit gate.
        
        Parameters
        ----------
        name : str
            Name of the gate
        qubits : list of int
            Qubit indices the gate acts on
        params : dict, optional
            Parameters for the gate (e.g., {'angle': theta})
        matrix : Qobj, optional
            Unitary matrix representation
        """
        self.name = name
        self.qubits = qubits
        self.params = params or {}
        self.matrix = matrix
    
    def __repr__(self):
        param_str = ""
        if self.params:
            param_str = f"({', '.join(f'{k}={v:.4f}' for k, v in self.params.items())})"
        qubit_str = ','.join(map(str, self.qubits))
        return f"{self.name}{param_str}[{qubit_str}]"


class QuantumCircuit:
    """
    Represents a quantum circuit as a sequence of gates.
    
    This class stores the structure of a quantum circuit and provides
    methods for visualization.
    
    Attributes
    ----------
    num_qubits : int
        Number of qubits in the circuit
    gates : list of CircuitGate
        List of gates in the circuit
    metadata : dict
        Additional metadata about the circuit
    """
    
    def __init__(self, num_qubits: int):
        """
        Initialize a quantum circuit.
        
        Parameters
        ----------
        num_qubits : int
            Number of qubits in the circuit
        """
        self.num_qubits = num_qubits
        self.gates = []
        self.metadata = {}
    
    def add_gate(self, gate: CircuitGate):
        """
        Add a gate to the circuit.
        
        Parameters
        ----------
        gate : CircuitGate
            Gate to add to the circuit
        """
        # Validate qubit indices
        for q in gate.qubits:
            if q < 0 or q >= self.num_qubits:
                raise ValueError(f"Invalid qubit index {q} for {self.num_qubits}-qubit circuit")
        self.gates.append(gate)
    
    def add_rotation(self, axis: str, angle: float, qubit: int, matrix: Optional[qt.Qobj] = None):
        """
        Add a rotation gate to the circuit.
        
        Parameters
        ----------
        axis : str
            Rotation axis ('X', 'Y', or 'Z')
        angle : float
            Rotation angle in radians
        qubit : int
            Qubit index
        matrix : Qobj, optional
            Unitary matrix representation
        """
        gate_name = f"R{axis.upper()}"
        gate = CircuitGate(gate_name, [qubit], {'angle': angle}, matrix)
        self.add_gate(gate)
    
    def add_exp_operator(self, operator: qt.Qobj, time: float, label: str = "exp"):
        """
        Add a general exponential operator exp(-i*operator*time).
        
        This method decomposes the operator into rotation gates on the qubits.
        
        Parameters
        ----------
        operator : Qobj
            The operator to exponentiate
        time : float
            Time parameter
        label : str
            Label for this operation
        """
        # For a 2-qubit operator, we decompose it into elementary gates
        # This is the key method that creates the actual circuit from the Trotter steps
        
        if operator.shape != (4, 4):
            raise ValueError("Operator must be 4x4 for 2-qubit encoding")
        
        # Decompose the operator into basis gates
        # For now, we represent it as a general unitary operation
        # This could be further decomposed using techniques like KAK decomposition
        
        # Get the matrix
        U = (-1j * operator * time).expm()
        
        # For visualization purposes, we'll represent this as a multi-qubit gate
        gate = CircuitGate(
            name=f"U({label})",
            qubits=[0, 1],
            params={'time': time},
            matrix=U
        )
        self.add_gate(gate)
    
    def depth(self) -> int:
        """
        Calculate the depth of the circuit.
        
        Returns
        -------
        depth : int
            Circuit depth (number of time steps)
        """
        if not self.gates:
            return 0
        
        # Track the last time each qubit was used
        qubit_times = [0] * self.num_qubits
        
        for gate in self.gates:
            # Find the earliest time this gate can be applied
            max_time = max(qubit_times[q] for q in gate.qubits)
            # Update times for all qubits involved
            for q in gate.qubits:
                qubit_times[q] = max_time + 1
        
        return max(qubit_times)
    
    def to_text(self) -> str:
        """
        Generate a text representation of the circuit.
        
        Returns
        -------
        text : str
            Text-based circuit diagram
        """
        if not self.gates:
            return "Empty circuit"
        
        # Create a simple text representation
        lines = []
        lines.append(f"Quantum Circuit ({self.num_qubits} qubits, {len(self.gates)} gates, depth {self.depth()})")
        lines.append("=" * 60)
        
        for i, gate in enumerate(self.gates):
            lines.append(f"Step {i+1}: {gate}")
        
        return "\n".join(lines)
    
    def to_qiskit(self):
        """
        Convert the quantum circuit to Qiskit format.
        
        This method converts the custom circuit representation to a Qiskit
        QuantumCircuit object. Each gate with a matrix representation is
        converted to a Qiskit Unitary gate.
        
        Returns
        -------
        qiskit_circuit : qiskit.QuantumCircuit
            The equivalent Qiskit quantum circuit
            
        Raises
        ------
        ImportError
            If Qiskit is not installed
        ValueError
            If a gate doesn't have a matrix representation
        """
        if not QISKIT_AVAILABLE:
            raise ImportError("Qiskit is not installed. Please install it with: pip install qiskit")
        
        # Create a Qiskit circuit with the same number of qubits
        qc = QiskitQuantumCircuit(self.num_qubits)
        
        # Convert each gate
        for gate in self.gates:
            if gate.matrix is None:
                raise ValueError(f"Gate {gate.name} does not have a matrix representation")
            
            # Get the unitary matrix from the Qobj
            matrix = gate.matrix.data.to_array()
            
            # Convert to Qiskit Operator and add as unitary gate
            operator = Operator(matrix)
            
            # Apply the unitary to the specified qubits
            # Qiskit uses little-endian convention, so we need to reverse qubit order
            qubits_qiskit = list(reversed(gate.qubits))
            qc.unitary(operator, qubits_qiskit, label=gate.name)
        
        return qc
    
    def visualize(self, fig=None, ax=None, title: Optional[str] = None):
        """
        Visualize the quantum circuit using matplotlib.
        
        Parameters
        ----------
        fig : matplotlib.figure.Figure, optional
            Figure to plot on
        ax : matplotlib.axes.Axes, optional
            Axes to plot on
        title : str, optional
            Title for the circuit diagram
            
        Returns
        -------
        fig : Figure
            The matplotlib figure
        ax : Axes
            The matplotlib axes
        """
        import matplotlib.pyplot as plt
        from matplotlib.patches import Rectangle, FancyBboxPatch
        
        if fig is None or ax is None:
            fig, ax = plt.subplots(figsize=(max(12, len(self.gates) * 0.8), 4))
        
        # Circuit visualization parameters
        qubit_spacing = 1.0
        gate_width = 0.6
        gate_height = 0.4
        gate_spacing = 1.0
        
        # Draw qubit lines
        max_x = len(self.gates) * gate_spacing + 1
        for i in range(self.num_qubits):
            y = (self.num_qubits - 1 - i) * qubit_spacing
            ax.plot([0, max_x], [y, y], 'k-', linewidth=1)
            ax.text(-0.5, y, f'q{i}', ha='right', va='center', fontsize=12)
        
        # Draw gates
        gate_positions = {}  # Track position for each gate
        qubit_positions = [0.5] * self.num_qubits  # Track current x position for each qubit
        
        for gate_idx, gate in enumerate(self.gates):
            # Find the x position for this gate
            x_pos = max(qubit_positions[q] for q in gate.qubits)
            
            if len(gate.qubits) == 1:
                # Single-qubit gate
                q = gate.qubits[0]
                y = (self.num_qubits - 1 - q) * qubit_spacing
                
                # Draw gate box
                box = FancyBboxPatch(
                    (x_pos - gate_width/2, y - gate_height/2),
                    gate_width, gate_height,
                    boxstyle="round,pad=0.05",
                    edgecolor='blue', facecolor='lightblue',
                    linewidth=1.5
                )
                ax.add_patch(box)
                
                # Add gate label
                gate_label = gate.name
                if 'angle' in gate.params:
                    angle = gate.params['angle']
                    gate_label += f"\n{angle:.3f}"
                ax.text(x_pos, y, gate_label, ha='center', va='center', 
                       fontsize=9, weight='bold')
                
            else:
                # Multi-qubit gate
                qubit_ys = [(self.num_qubits - 1 - q) * qubit_spacing for q in gate.qubits]
                y_min, y_max = min(qubit_ys), max(qubit_ys)
                
                # Draw vertical connection line
                ax.plot([x_pos, x_pos], [y_min, y_max], 'b-', linewidth=2)
                
                # Draw gate boxes at each qubit
                for q in gate.qubits:
                    y = (self.num_qubits - 1 - q) * qubit_spacing
                    circle = plt.Circle((x_pos, y), 0.15, color='blue', zorder=10)
                    ax.add_patch(circle)
                
                # Add label in the middle
                y_mid = (y_min + y_max) / 2
                gate_label = gate.name
                if 'time' in gate.params:
                    gate_label += f"\ndt={gate.params['time']:.3f}"
                
                # Draw a box for the label
                bbox_props = dict(boxstyle="round,pad=0.3", facecolor='lightyellow', 
                                edgecolor='blue', linewidth=1.5)
                ax.text(x_pos, y_mid, gate_label, ha='center', va='center',
                       fontsize=9, weight='bold', bbox=bbox_props)
            
            # Update positions
            for q in gate.qubits:
                qubit_positions[q] = x_pos + gate_spacing
        
        # Set axis properties
        ax.set_xlim(-1, max_x + 0.5)
        ax.set_ylim(-0.5, self.num_qubits * qubit_spacing)
        ax.set_aspect('equal')
        ax.axis('off')
        
        if title:
            ax.set_title(title, fontsize=14, weight='bold', pad=20)
        
        return fig, ax


def decompose_trotter_circuit(hamiltonian_terms: List[qt.Qobj], dt: float, 
                              order: int = 2, num_steps: int = 1) -> QuantumCircuit:
    """
    Create a quantum circuit representation of a Suzuki-Trotter decomposition.
    
    This function creates a circuit that represents the time evolution under
    a Hamiltonian decomposed using Suzuki-Trotter methods.
    
    Parameters
    ----------
    hamiltonian_terms : list of Qobj
        List of Hamiltonian terms [H1, H2, ...]
    dt : float
        Time step for evolution
    order : int
        Order of Trotter decomposition (1, 2, or 4)
    num_steps : int
        Number of time steps to include in the circuit
        
    Returns
    -------
    circuit : QuantumCircuit
        Quantum circuit representing the Trotter decomposition
    """
    # Assume 2-qubit encoding (4x4 operators)
    circuit = QuantumCircuit(num_qubits=2)
    
    # Store metadata
    circuit.metadata = {
        'order': order,
        'dt': dt,
        'num_steps': num_steps,
        'num_terms': len(hamiltonian_terms)
    }
    
    for step in range(num_steps):
        if order == 1:
            # First-order: exp(-iH1*dt) * exp(-iH2*dt) * ...
            for i, H_i in enumerate(hamiltonian_terms):
                circuit.add_exp_operator(H_i, dt, label=f"H{i+1}")
                
        elif order == 2:
            # Second-order: exp(-iH1*dt/2) * exp(-iH2*dt/2) * ... 
            #                * exp(-iHn*dt) * ...
            #                * exp(-iH2*dt/2) * exp(-iH1*dt/2)
            n = len(hamiltonian_terms)
            
            # Forward sweep (half steps for all but last)
            for i in range(n - 1):
                circuit.add_exp_operator(hamiltonian_terms[i], dt/2, label=f"H{i+1}")
            
            # Full step for last term
            circuit.add_exp_operator(hamiltonian_terms[n-1], dt, label=f"H{n}")
            
            # Backward sweep (half steps in reverse)
            for i in range(n - 2, -1, -1):
                circuit.add_exp_operator(hamiltonian_terms[i], dt/2, label=f"H{i+1}")
                
        elif order == 4:
            # Fourth-order using Yoshida coefficients
            p = 1.0 / (4.0 - 4.0 ** (1.0/3.0))
            
            # Apply composition of second-order steps
            for coeff, label in [(p, "S2(p)"), (p, "S2(p)"), 
                                (1.0 - 4.0*p, "S2(1-4p)"), 
                                (p, "S2(p)"), (p, "S2(p)")]:
                n = len(hamiltonian_terms)
                # Second-order step with scaled time
                for i in range(n - 1):
                    circuit.add_exp_operator(hamiltonian_terms[i], coeff*dt/2, 
                                           label=f"{label}_H{i+1}")
                circuit.add_exp_operator(hamiltonian_terms[n-1], coeff*dt, 
                                       label=f"{label}_H{n}")
                for i in range(n - 2, -1, -1):
                    circuit.add_exp_operator(hamiltonian_terms[i], coeff*dt/2, 
                                           label=f"{label}_H{i+1}")
    
    return circuit
